services:
  stud-backend:
    container_name: stud-backend
    hostname: backend
    build:
      context: ../
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend.env
    depends_on:
      stud-postgres:
        condition: service_healthy
      stud-minio:
        condition: service_healthy
    networks:
      - stud-postgres
      - stud-minio
      - stud-front-back

  stud-postgres:
    container_name: stud-postgres
    hostname: stud-postgres
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    env_file:
      - pg.env
    ports:
      - "5432:5432"
    healthcheck:
      # Need to get data from env file
      test: ["CMD-SHELL", "pg_isready -U stud -d stud"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - stud-db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - stud-postgres


  stud-pg-migrator:
    container_name: stud-pg-migrator
    depends_on: [stud-postgres]
    env_file:
      - migr.env
    build:
      context: ../
      dockerfile: ./migrations/Dockerfile
    networks:
      - stud-postgres
  
  stud-minio:
    container_name: stud-minio
    hostname: stud-minio
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    command: server --console-address ":9001" --address ":9000" /data
    env_file:
      - minio.env
    volumes:
      - stud-minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - stud-minio
      - stud-front-back
    
  stud-minio-migrate:
    container_name: stud-minio-migrate
    depends_on:
      - stud-minio
    build:
      context: ../
      dockerfile: ./pkg/minio/Dockerfile
    env_file: 
      - minio.env
    networks:
      - stud-minio

volumes:
  stud-db-data:
  stud-minio-data:

networks:
  stud-postgres:
    driver: bridge
  stud-minio:
    driver: bridge
  stud-front-back:
    driver: bridge
    external: true

